package pt.unl.fct.iadi.bookstore.controller.dto

import io.swagger.v3.oas.annotations.media.Schema
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import java.util.UUID

data class ReviewDTO(
    @field:Schema(description = "The unique ID of the review (generated by server)",
        example = "550e8400-e29b-41d4-a716-446655440000", accessMode = Schema.AccessMode.READ_ONLY)
    val id: String?,

    @field:NotBlank
    @field:Size(min = 1, max = 50, message = "The review author name must be between 1 and 50 characters")
    @field:Schema(description = "The name of the author of the review", example = "John Smith")
    val author: String,

    @field:NotNull(message = "Rating must be provided")
    @field:Min(value = 1, message = "Rating must be between 1 and 5")
    @field:Max(value = 5, message = "Rating must be between 1 and 5")
    @field:Schema(description = "Rating from 1 to 5",
        minimum = "1", maximum = "5", example = "5")
    val rating: Int,

    @field:NotNull
    @field:Size(min = 0, max = 500, message = "Comment must be between 0 and 500",)
    @field:Schema(description = "Optional text comment",
        maxLength = 500, example = "Excellent read!")
    val comment: String?
) {
}