package pt.unl.fct.iadi.bookstore.controller.dto

import io.swagger.v3.oas.annotations.media.Schema
import java.util.UUID

data class ReviewDTO(
    @Schema(description = "The unique ID of the review (generated by server)",
        example = "550e8400-e29b-41d4-a716-446655440000", accessMode = Schema.AccessMode.READ_ONLY)
    val id: UUID?,
    @Schema(description = "Rating from 1 to 5",
        minimum = "1", maximum = "5", example = "5")
    val rating: Int,
    @Schema(description = "Optional text comment",
        maxLength = 500, example = "Excellent read!")
    val comment: String?
) {
}